name: deploy spring app on onprem

on:
  workflow_dispatch:

jobs:
  pre-check:
    runs-on: onprem-runner
    steps:
      - uses: actions/checkout@v3
      - name: check the versions
        run: |
          setx PATH "$env:path;C:\opt\apache-maven-3.8.6\bin" -m
          mvn --version
          java --version

  build:
    runs-on: onprem-runner
    needs: pre-check
    steps:
      - uses: actions/checkout@v3
      - name: build the code
        run: |
           mvn clean package

  deploy:
    runs-on: onprem-runner
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: deploy the code on onprem
        run: |
          java -jar .\target\HelloWorld-0.0.1-SNAPSHOT.jar